#!/usr/bin/env python3

##
## EPITECH PROJECT, 2020
## launcher
## File description:
## launcher to load or create a new game
##

import sys
import pygame
from pygame.locals import *

sys.path.insert(1, "./src/")

import player
import event as Ev
import display as Disp
import options
import map
import images_load
import monster

pygame.init()
pygame.mixer.init()

class Launcher(object):

    window = pygame.display.set_mode((1240, 800))
    font = pygame.font.Font("data/font/rpgfont.ttf", 60)
    small_font = pygame.font.Font("data/font/rpgfont.ttf", 20)
    mobs = [monster.Monster()]
    page = 0
    fen = 0
    mouse = (0, 0)
    p = player.Player()
    option = options.Options()
    map_collisions = map.get_map("map1")
    move_keys = [False, False, False, False, False]
    keys = {"Escape": False, "Inventory": False}
    refresh_time = 0
    items = []
    index_animation = 0

    def __init__(self):
        self.images = images_load.get_image(self)
        pygame.display.set_caption("The Legend of Paradou")
        pygame.mixer.music.load("data/music/Theme2.ogg")
        pygame.mixer.music.play(loops=-1)

    def refresh(self):
        global opened_window
        clock = pygame.time.Clock()

        while True:
            clock.tick(120)
            self.window.fill((0, 0, 0))
            self.refresh_time += 1
            if self.refresh_time > 60:
                self.refresh_time = 0
            self.display()
            self.event()
            pygame.display.flip()

    def event(self):
        for event in pygame.event.get():
            self.mouse = pygame.mouse.get_pos()
            if self.fen == 0 and self.page == 0:
                Ev.event_main_menu(event, self)
            if self.fen == 0 and self.page == 2:
                Ev.event_options(event, self)
            if self.fen == 1 and self.page == 0:
                Ev.event_game(event, self)
            if self.fen == 1 and self.page == 1:
                Ev.event_menu(event, self)
            if self.fen == 1 and self.page == 2:
                Ev.event_inventory(event, self)
            if self.fen == 1 and self.page == 3:
                Ev.event_option_game(event, self)

    def display(self):
        if self.fen == 0:
            if self.page == 0:
                Disp.display_main_menu(self)
            elif self.page == 1:
                pass
            elif self.page == 2:
                Disp.display_options(self)
        if self.fen == 1:
            if self.page == 0:
                Disp.display_map(self)
            if self.page == 1:
                Disp.display_menu(self)
            if self.page == 2:
                Disp.display_inventory(self)
            if self.page == 3:
                Disp.display_option_game(self)

Launcher().refresh()