#!/usr/bin/env python3

##
## EPITECH PROJECT, 2020
## launcher
## File description:
## launcher to load or create a new game
##

import pygame
from pygame.locals import *
import player
import event as Ev
import display as Disp

pygame.init()
pygame.mixer.init()

class Launcher(object):

    window = pygame.display.set_mode((1240, 800))
    font = pygame.font.Font("data/font/rpgfont.ttf", 60)
    page = 0
    fen = 0
    mouse = (0, 0)
    p = player.Player()

    def __init__(self):
        pygame.display.set_caption("The Legend of Paradou")
        pygame.mixer.music.load("data/music/Theme2.ogg")
        pygame.mixer.music.play(loops=-1)

    def refresh(self):
        global opened_window
        clock = pygame.time.Clock()

        while True:
            self.window.fill((0, 0, 0))
            clock.tick(60)
            self.display()
            self.event()
            pygame.display.flip()

    def event(self):
        for event in pygame.event.get():
            self.mouse = pygame.mouse.get_pos()
            if self.fen == 0:
                Ev.event_main_menu(event, self)

    def display(self):
        if self.fen == 0:
            if self.page == 0:
                Disp.display_main_menu(self)
            elif self.page == 1:
                Disp.display_options(self)

Launcher().refresh()