#!/usr/bin/env python3

import pygame
from pygame.locals import *

pygame.init()
pygame.mixer.init()

class Launcher(object):

    window = pygame.display.set_mode((900, 800))
    font = pygame.font.Font("data/font/rpgfont.ttf", 12)

    def __init__(self):
        pygame.display.set_caption("The Legend of Paradou")
        pygame.mixer.music.load("data/music/Theme2.ogg")
        pygame.mixer.music.play(loops=-1)

    def intro(self):
        clock = pygame.time.Clock()
        while True:
            self.window.fill((0, 0, 0))
            clock.tick(60)
            for event in pygame.event.get():
                if event.type == QUIT:
                    exit(0)
            pygame.display.flip()

Launcher().intro()