#!/usr/bin/env python3

import pygame

class Launcher(object):

    window = pygame.display.set_mode((900, 800))
    font = pygame.font.Font("data/font/rpgfont.ttf", 12)

    def __init__(self):
        pygame.display.set_caption("The Legend of Paradou")

    def intro(self):
        pass

pygame.init()
pygame.mixer.init()

Launcher().intro()